name: farm_role_roles (deprecated)
description: This module has moved to the farm_manager, farm_worker, and farm_viewer modules.
type: module
package: farmOS (deprecated)
core_version_requirement: ^11
lifecycle: obsolete
lifecycle_link: 'https://www.drupal.org/node/3527787'
dependencies:
  - farm:farm_manager
  - farm:farm_worker
  - farm:farm_viewer
